ens_simon:
    resource: "@EnsSimonBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

EnsSimonBundle_category:
    path:  /category/{slug}
    defaults: { _controller: EnsSimonBundle:Category:show }