ens_simon_job:
    resource: "@EnsSimonBundle/Resources/config/routing/job.yml"
    prefix:   /job

EnsSimonBundle_category:
    path:  /category/{slug}/{page}
    defaults: { _controller: EnsSimonBundle:Category:show, page: 1 }

ens_simon_homepage:
    path:     /
    defaults: { _controller: EnsSimonBundle:Job:index }
